#!/usr/bin/env bash
# Phase 2 -- the lexical-locality test, in dependency order.
#
# Every command is also listed individually in docs/REPRODUCE.md; this file exists so the
# chain can be replayed unattended. It never writes to a phase-1 output directory: the
# phase-2 dataset is `pilot_50k_p2` and the runs are `*_p2`, `*_p2guided_*`,
# `*_p2bestofn_*`.
#
#   bash scripts/run_phase2.sh <stage>
#
# Stages: setup | breadth | headroom | central | scatter | all
set -euo pipefail
cd "$(dirname "$0")/.."
PY=.venv/bin/python
DS=pilot_50k_p2
HEADS=pilot_50k_heads_p2
LOG=outputs/phase2.log

log() { echo "=== $(date -Is) $* ===" | tee -a "$LOG"; }
run() { log "$*"; "$@" 2>&1 | grep -Ev "fast_transformers|Falling back|attention_mask|We strongly" | tee -a "$LOG"; }

STAGE="${1:-all}"

if [[ "$STAGE" == "setup" || "$STAGE" == "all" ]]; then
  # Device equivalence, including whether wall time reproduces on this machine.
  # Run with nothing else on the GPU or the timing measurement is meaningless.
  run $PY scripts/13_device_equivalence.py --n-molecules 64 --timing-repeats 3

  # The phase-2 dataset. Frozen pilot intervals are INHERITED, not re-derived: the
  # regenerated sample is a different draw (pilot_report.md §11.2).
  run $PY scripts/02_generate_trajectories.py --config pilot_50k --out $DS \
      --inherit-intervals outputs/pilot_50k/target_intervals.json
fi

if [[ "$STAGE" == "breadth" || "$STAGE" == "all" ]]; then
  # Heads for all seven properties, three head seeds each. --head-seeds also seeds
  # initialisation, which the pilot did not.
  run $PY scripts/03_train_heads.py --dataset $DS --config pilot_50k \
      --head-seeds 1234 2345 3456 --out $HEADS

  # The same heads under the pilot's un-aligned interval mask, one seed, purely to
  # quantify what that defect cost (pilot_report.md §11.5). Not used downstream.
  run $PY scripts/03_train_heads.py --dataset $DS --config pilot_50k \
      --head-seeds 1234 --legacy-interval-mask --out ${HEADS}_legacymask
  run $PY scripts/14_interval_mask_impact.py --fixed $HEADS --legacy ${HEADS}_legacymask

  # Rollout bank: predictability against the distribution the frozen model actually
  # produces. A new bank, because the pilot's stores property values and not the
  # rollout SMILES, so the four new properties cannot be added to it after the fact.
  run $PY scripts/04_rollout_bank.py --dataset $DS --heads $HEADS \
      --n-prefixes 800 --n-rollouts 32 --out ${DS}_rollouts
fi

if [[ "$STAGE" == "headroom" || "$STAGE" == "all" ]]; then
  # The head-free, lambda-free ceiling. 400 prefixes x 8 candidates x 16 rollouts.
  run $PY scripts/11_steering_headroom.py --dataset $DS --heads $HEADS \
      --n-prefixes 400 --n-rollouts 16 --out ${DS}_headroom
fi

if [[ "$STAGE" == "central" || "$STAGE" == "all" ]]; then
  # Ordered so the discriminating case (hbd_count, SLIM's hardest property under
  # additive latent steering) lands early rather than last.
  # Output directories are the scripts' own defaults for this dataset, i.e.
  # pilot_50k_p2_guided_<prop> and pilot_50k_p2_bestofn_<prop>, which is why no phase-1
  # directory can be touched: the dataset name differs.
  for prop in aromatic_rings hbd_count rotatable_bonds tpsa clogp qed; do
    run $PY scripts/05_guided_generation.py --dataset $DS --heads $HEADS --property "$prop"
    run $PY scripts/06_best_of_n.py --dataset $DS --property "$prop" --full-recompute-n 64
    run $PY scripts/09_confound_analysis.py --dataset $DS --property "$prop"
    run $PY scripts/10_quality_analysis.py --dataset $DS --property "$prop"
  done

  # Does the section 11.5 interval-mask defect change guided decoding at all? Same
  # dataset, same seeds, only the head's mask differs. A softmax over candidates is
  # invariant to an additive constant, so a uniform shrink of every candidate's target
  # probability should very nearly cancel -- measured rather than argued.
  run $PY scripts/05_guided_generation.py --dataset $DS --heads ${HEADS}_legacymask \
      --property clogp --conditions unguided throughout \
      --out ${DS}_guided_clogp_legacymask
fi

if [[ "$STAGE" == "lambda" || "$STAGE" == "all" ]]; then
  # C10 -- the lambda sweep, on three ANCHOR properties chosen by a rule fixed before
  # the sweep ran: the most steerable at lambda=1 (aromatic_rings, +0.2949), the least
  # steerable (qed, +0.1012), and the pre-registered discriminating case (hbd_count).
  # Depth on anchors, breadth at lambda=1 elsewhere -- docs/TODO.md section E rules out
  # the full lambda x property grid.
  #
  # lambda=1 is NOT re-run: the central-test directories already hold it, generated by
  # this same script with the same seeds, n, head and backend.
  #
  # Only `unguided` and `throughout` are generated. The other four conditions do not
  # depend on lambda in a way this sweep asks about: `truncation_control` is lambda=0
  # by definition and the three window conditions are a separate axis. `unguided` is
  # regenerated at every lambda even though it cannot depend on lambda, because
  # best-of-N is matched against the base tokens/molecule measured in the same run --
  # and because an unguided hit rate that moved would be a bug alarm.
  # Only the `actual` accounting is matched here. Under `full_recompute` the budget is
  # N ~ 200 independent base-policy draws against a base rate of 0.08-0.17, so best-of-N
  # returns a hit with probability 1 - (1-p)^N > 1 - 1e-7: it measured exactly 1.0000 for
  # all six properties at lambda = 1 (section 16.2) and cannot do anything else at any
  # lambda, since no guided hit rate can exceed 1. Spending ~70% of the sweep's compute
  # re-confirming a saturated baseline buys nothing. `n_candidates_full_recompute` is
  # still recorded per run so the saturation argument can be checked rather than assumed.
  for prop in aromatic_rings hbd_count qed; do
    for lam in 0.25 0.5 2 4 8; do
      tag="lam$(echo "$lam" | tr '.' 'p')"
      # Idempotent: a completed combination is not regenerated, so the stage can be
      # resumed after an interruption without discarding finished work.
      [[ -f outputs/${DS}_${tag}_guided_${prop}/guidance_metrics.json ]] || \
      run $PY scripts/05_guided_generation.py --dataset $DS --heads $HEADS \
          --property "$prop" --lam "$lam" --conditions unguided throughout \
          --out ${DS}_${tag}_guided_${prop}
      [[ -f outputs/${DS}_${tag}_bestofn_${prop}/bestofn_metrics.json ]] || \
      run $PY scripts/06_best_of_n.py --dataset $DS --property "$prop" \
          --guided ${DS}_${tag}_guided_${prop} --accounting actual \
          --out ${DS}_${tag}_bestofn_${prop}
      # C12: quality at EVERY lambda. The pilot's null result on quality is specific to
      # lambda=1 into a bounded interval; high lambda is where the literature's
      # degenerate molecules should appear, so this is a real prediction being tested.
      [[ -f outputs/${DS}_${tag}_quality_${prop}/quality_metrics.json ]] || \
      run $PY scripts/10_quality_analysis.py --dataset $DS --property "$prop" \
          --guided ${DS}_${tag}_guided_${prop} --out ${DS}_${tag}_quality_${prop}
    done
  done
fi

if [[ "$STAGE" == "scatter" || "$STAGE" == "all" ]]; then
  run $PY scripts/12_locality_scatter.py --dataset $DS \
      --headroom ${DS}_headroom --heads $HEADS \
      --guided-suffix guided --bestofn-suffix bestofn \
      --out ${DS}_locality
  run $PY scripts/07_figures.py --dataset $DS --heads $HEADS \
      --rollouts ${DS}_rollouts --guided-suffix guided --bestofn-suffix bestofn \
      --out $DS
fi

log "phase 2 stage '$STAGE' complete"
